name: production cd pipeline

on:
  push:
    branches:
      - main
    paths:
      - K8-manifest/prod.app-deploy
      - .github/workflows/prod-cicd.yml

      permisions:
      contents: write
      id-token: write

      jobs:
      promote-image-to-prod:
      name: Pull QA latest and retag for prod
      runs-on: ubuntu-latest

env:
QA_IMAGE: mayankdev12/nodejs-app:latest
PROD_LATEST_IMAGE: mayankdev12/nodejs-app-${{github.sha}}

steps:
- name: login to docker hub
uses: docker/login-action@v4
with:
username: ${{vars.DOCKERHUB_USERNAME}}
password: ${{secrets.DOCKERHUB_TOKEN}}

- name: PULL QA latest image
run: docker pull "${QA_IMAGE}"

- name: retag image for production
run: |
docker tag "${QA_IMAGE}" "${PROD_LATEST_IMAGE}"

- name: Push prod images
run: |
docker push "${PROD_LATEST_IMAGE}"


update-prod-manifest:
name: update prod manifest
needs: promote-image-to-prod
runs-on: ubuntu-latest
permissions:
contents: write
id-token: write


steps:
- name: checkout main branch
uses: actions/checkout@v4
with:
ref: main

 - name: update image tag in manifest
        run: |
          sed -i "s|image:mayankdev12/nodejs-app:.*|image:mayankdev12/nodejs-app:${GITHUB_SHA}|g" K8-manifest/prod/app-deployment.yaml

      - name: Show updated manifest(debug)
        run: |
          cat K8-manifest/app-deployment.yaml

      - name: commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add K8-manifest/prod/app-deployment.yaml
          git commit -m "update QA image to ${GITHUB_SHA} [skip ci]" || echo "no changes to commit"
          git push origin main 


